### ISSUE TITLE
Getting error in log  Record not found

### ISSUE THREAD

**Issue by awestwell** [muka/dyndns#1]
Good Day 

1. Install using docker-compose

```
    ddns:
        container_name: ddns
        image: raptorbox/ddns-amd64
        restart: always
        ports:
            - 5303:5303
            - 5303:5303/udp
            - 50053:50053
        environment:
            - PUID=${DOCKER_PUID}
            - PGID=${DOCKER_PGID}
            - TZ=${DOCKER_TZ}
        networks:
           shared-vlan:
               ipv4_address: 10.22.200.14
        volumes:
            - ${DOCKER_CONTAINERS}/ddns/data:/data

```
2. Execute curl command to add a record

```
curl -X POST http://10.22.200.14:5551/v1/record   -H 'content-type: application/json'     -d '{
"ip": "10.22.22.22",
"domain": "foobar.local.lan",
"type": "A",
"expires": 1498454965
}'
```

JSON Response:
`{"ip":"10.22.22.22","domain":"foobar.local.lan","type":"A","expires":1498454965}`

3. Executing nslookup command 
```
nslookup foobar.local.lan 10.22.200.14 -port=10053
Server:		10.22.200.14
Address:	10.22.200.14#10053

** server can't find foobar.local.lan: NXDOMAIN
```
In docker logs for the container I see the following
`time="2022-03-23T00:52:54Z" level=info msg="Record not found, key:  lan.local.foobar_1"` 

I would expect the query to return correctly
